---
default_stages: [push]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace #This hook trims all whitespace from the end of each line
          - id: end-of-file-fixer #This hooks ensures that all files end in a newline and only a newline.
          - id: mixed-line-ending # This hook replaces or checks mixed line ending.
          - id: check-yaml #This hook will attempt to load all yaml files and verify their syntax
          - id: check-added-large-files # this hook will prevent extremely large files from being committed.
            args: [--maxkb=20000]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
            args: [--width, '89']
    - repo: https://github.com/pycqa/flake8
      rev: 7.0.0
      hooks:
          - id: flake8
    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
          - id: black
    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: [--profile, black, --filter-files]
    - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
      rev: v0.0.265
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]
    - repo: https://github.com/Yelp/detect-secrets
      rev: v1.5.0
      hooks:
          - id: detect-secrets
            args: [--baseline, .secrets.baseline]    # TODO(potential): Include GCloud token regex
            exclude: package.lock.json
    - repo: https://github.com/astral-sh/uv-pre-commit
      # uv version.
      rev: 0.6.16
      hooks:
          - id: uv-lock
          - id: uv-export
            args: [--frozen, --no-hashes, --no-emit-project, --all-groups, --output-file=requirements-dev.txt]

#  - repo: https://github.com/econchick/interrogate
#    rev: 1.7.0
#    hooks:
#      - id: interrogate
#        args: [-vv, -i, --fail-under=95]
