---
name: pre-commit

on: # This will trigger the job on any file change
    pull_request:
    push:

jobs:
    uv-example:
        name: python
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                  # Install a specific version of uv.
                  version: 0.6.16

            - name: Install the project
              run: uv sync --locked --all-extras --dev

            - name: Run tests
        # For example, using `pytest`
              run: uv run pre-commit run --all-files --hook-stage push --verbose
